services:
  jenkins:
    image: jenkins/jenkins:2.401.2-jdk11
    container_name: jenkins
    privileged: true
    user: root
    ports:  
      - "8080:8080"
    volumes:
      - ${PWD}/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  ssh-agent:
    build: ./
    container_name: agent
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFMPooRI9R75o6jPog36Z9mkaIFo0oUrioTF6b3LNoog kbednarczyk@C12813
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
  ssh-agent-17:
    build: 
      context: ./
      dockerfile: agent.Dockerfile
    container_name: agent-jdk17
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFMPooRI9R75o6jPog36Z9mkaIFo0oUrioTF6b3LNoog kbednarczyk@C12813
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins  